services:
  postgres:
    image: postgres:17
    environment:
      POSTGRES_USER: marsa
      POSTGRES_PASSWORD: marsa
      POSTGRES_DB: marsa_test
    ports:
      - '5432:5432'
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
