// This file is auto-generated by @hey-api/openapi-ts

export type ClientOptions = {
  baseUrl: string
}

export type GetApiInfoResponse = {
  name: string
  version: string
  commit: string | null
  nodeEnv: string
  uptimeSeconds: number
}

export type HookAttributesDto = {
  /**
   * Webhook delivery URL.
   */
  url: string
}

export type ManifestDto = {
  name: string
  url: string
  hook_attributes: HookAttributesDto
  redirect_url: string
  callback_urls: Array<string>
  public: boolean
  request_oauth_on_install: boolean
  default_permissions: {
    [key: string]: string
  }
  default_events: Array<string>
}

export type GetManifestResponse = {
  /**
   * GitHub App manifest — the FE posts this as the `manifest` form field.
   */
  manifest: ManifestDto
  /**
   * Form action the FE submits the manifest to.
   */
  formAction: string
  /**
   * Single-use CSRF state token (DB-backed, expires in 10 min); echoed back by GitHub on the callback.
   */
  state: string
}

export type ConvertManifestCommand = {
  /**
   * Temporary code from the GitHub redirect.
   */
  code: string
  /**
   * Signed CSRF state echoed back by GitHub.
   */
  state: string
}

export type ConvertManifestResponse = {
  appSlug: string
  appName: string
  htmlUrl: string
  /**
   * Where the operator installs the App on their repos (#23).
   */
  installUrl: string
}

export type CaptureInstallationCommand = {
  /**
   * GitHub's numeric installation id from the post-install redirect.
   */
  installationId: string
  /**
   * GitHub's `setup_action` query param (expected: `install`).
   */
  setupAction: 'install'
}

export type CaptureInstallationResponse = {
  installationId: string
  accountLogin: string | null
  /**
   * True once the installation is captured and its access verified.
   */
  connected: boolean
}

export type CompleteGithubLoginCommand = {
  /**
   * GitHub's user-OAuth authorization code from the consent redirect.
   */
  code: string
  /**
   * The CSRF state issued by `GET /auth/github`, echoed back by GitHub.
   */
  state: string
}

export type CompleteGithubLoginResponse = {
  id: string
  login: string
}

export type GetCurrentUserResponse = {
  id: string
  login: string
}

export type GetApiInfoV1Data = {
  body?: never
  path?: never
  query?: never
  url: '/api/v1/status'
}

export type GetApiInfoV1Responses = {
  200: GetApiInfoResponse
}

export type GetApiInfoV1Response = GetApiInfoV1Responses[keyof GetApiInfoV1Responses]

export type GetGithubAppManifestV1Data = {
  body?: never
  path?: never
  query?: never
  url: '/api/v1/github-app/manifest'
}

export type GetGithubAppManifestV1Responses = {
  200: GetManifestResponse
}

export type GetGithubAppManifestV1Response =
  GetGithubAppManifestV1Responses[keyof GetGithubAppManifestV1Responses]

export type ConvertGithubAppManifestV1Data = {
  body: ConvertManifestCommand
  path?: never
  query?: never
  url: '/api/v1/github-app/convert-manifest'
}

export type ConvertGithubAppManifestV1Errors = {
  /**
   * Malformed body, or an invalid/expired state token.
   */
  400: unknown
  /**
   * GitHub App creation failed upstream at GitHub.
   */
  502: unknown
}

export type ConvertGithubAppManifestV1Responses = {
  200: ConvertManifestResponse
}

export type ConvertGithubAppManifestV1Response =
  ConvertGithubAppManifestV1Responses[keyof ConvertGithubAppManifestV1Responses]

export type CaptureGithubAppInstallationV1Data = {
  body: CaptureInstallationCommand
  path?: never
  query?: never
  url: '/api/v1/github-app/capture-installation'
}

export type CaptureGithubAppInstallationV1Errors = {
  /**
   * Malformed body, an unsupported setup_action, or no provisioned App.
   */
  400: unknown
  /**
   * The installation could not be verified with GitHub.
   */
  502: unknown
}

export type CaptureGithubAppInstallationV1Responses = {
  200: CaptureInstallationResponse
}

export type CaptureGithubAppInstallationV1Response =
  CaptureGithubAppInstallationV1Responses[keyof CaptureGithubAppInstallationV1Responses]

export type BeginGithubLoginV1Data = {
  body?: never
  path?: never
  query?: never
  url: '/api/v1/auth/github'
}

export type CompleteGithubLoginV1Data = {
  body: CompleteGithubLoginCommand
  path?: never
  query?: never
  url: '/api/v1/auth/github/session'
}

export type CompleteGithubLoginV1Errors = {
  /**
   * Invalid/expired OAuth state, or no provisioned App.
   */
  400: unknown
  /**
   * Could not complete login with GitHub.
   */
  502: unknown
}

export type CompleteGithubLoginV1Responses = {
  200: CompleteGithubLoginResponse
}

export type CompleteGithubLoginV1Response =
  CompleteGithubLoginV1Responses[keyof CompleteGithubLoginV1Responses]

export type GetCurrentUserV1Data = {
  body?: never
  path?: never
  query?: never
  url: '/api/v1/auth/me'
}

export type GetCurrentUserV1Errors = {
  /**
   * No active session.
   */
  401: unknown
}

export type GetCurrentUserV1Responses = {
  200: GetCurrentUserResponse
}

export type GetCurrentUserV1Response = GetCurrentUserV1Responses[keyof GetCurrentUserV1Responses]
