// This file is auto-generated by @hey-api/openapi-ts

export type ClientOptions = {
  baseUrl: string
}

export type GetApiInfoResponse = {
  name: string
  version: string
  commit: string | null
  nodeEnv: string
  uptimeSeconds: number
}

export type HookAttributesDto = {
  /**
   * Webhook delivery URL.
   */
  url: string
}

export type ManifestDto = {
  name: string
  url: string
  hook_attributes: HookAttributesDto
  redirect_url: string
  setup_url: string
  callback_urls: Array<string>
  public: boolean
  request_oauth_on_install: boolean
  default_permissions: {
    [key: string]: string
  }
  default_events: Array<string>
}

export type GetManifestResponse = {
  /**
   * GitHub App manifest — the FE posts this as the `manifest` form field.
   */
  manifest: ManifestDto
  /**
   * Form action the FE submits the manifest to.
   */
  formAction: string
  /**
   * Single-use CSRF state token (DB-backed, expires in 10 min); echoed back by GitHub on the callback.
   */
  state: string
}

export type ConvertManifestCommand = {
  /**
   * Temporary code from the GitHub redirect.
   */
  code: string
  /**
   * Signed CSRF state echoed back by GitHub.
   */
  state: string
}

export type ConvertManifestResponse = {
  appSlug: string
  appName: string
  htmlUrl: string
  /**
   * Where the operator installs the App on their repos (#23).
   */
  installUrl: string
}

export type CaptureInstallationCommand = {
  /**
   * GitHub's numeric installation id from the post-install redirect.
   */
  installationId: string
  /**
   * GitHub's `setup_action` query param (expected: `install`).
   */
  setupAction: 'install'
}

export type CaptureInstallationResponse = {
  installationId: string
  accountLogin: string | null
  /**
   * True once the installation is captured and its access verified.
   */
  connected: boolean
}

export type CompleteGithubLoginCommand = {
  /**
   * GitHub's user-OAuth authorization code from the consent redirect.
   */
  code: string
  /**
   * The CSRF state issued by `GET /auth/github`, echoed back by GitHub.
   */
  state: string
}

export type CompleteGithubLoginResponse = {
  id: string
  login: string
}

export type UserRole = 'operator' | 'member' | 'guest'

export type ViewMeResponse = {
  id: string
  login: string
  role: UserRole
}

export type ViewUserIndexQueryKey = {
  uuid: string
}

export type ViewUserIndexPaginationQuery = {
  limit?: number
  key?: ViewUserIndexQueryKey | null
}

export type UserSummary = {
  uuid: string
  githubUserId: string
  login: string
  role: UserRole
  createdAt: string
}

export type ViewUserIndexResponseMeta = {
  /**
   * Key for the next page, or null on the last page. Opaque — send it back as-is.
   */
  next: ViewUserIndexQueryKey | null
}

export type ViewUserIndexResponse = {
  /**
   * The items for the current page
   */
  items: Array<UserSummary>
  meta: ViewUserIndexResponseMeta
}

export type UpdateUserRoleCommand = {
  role: UserRole
}

export type UpdateUserRoleResponse = {
  uuid: string
  login: string
  role: UserRole
}

export type CreateReleaseCommand = {
  /**
   * Roll back: copy this release’s config instead of the app’s current config.
   */
  fromReleaseUuid?: string
}

export type ReleaseTrigger = 'manual' | 'webhook' | 'rollback'

export type CreateReleaseResponse = {
  releaseUuid: string
  appSlug: string
  triggeredBy: ReleaseTrigger
  sourceReleaseUuid: string | null
}

export type DeployStatus = 'pending' | 'in_progress' | 'succeeded' | 'failed'

export type DeployReleaseResponse = {
  releaseUuid: string
  appSlug: string
  url: string
  deployStatus: DeployStatus
}

export type ViewReleaseIndexQueryKey = {
  uuid: string
}

export type ViewReleaseIndexPaginationQuery = {
  limit?: number
  key?: ViewReleaseIndexQueryKey | null
}

export type ReleaseSummary = {
  uuid: string
  imageRef: string
  triggeredBy: ReleaseTrigger
  deployStatus: DeployStatus
  /**
   * Set on a rollback.
   */
  sourceReleaseUuid: string | null
  createdAt: string
  updatedAt: string
  /**
   * Why the deploy failed (live-derived, only on a failed release).
   */
  failureReason?: string | null
  failureMessage?: string | null
}

export type ViewReleaseIndexResponseMeta = {
  /**
   * Key for the next page, or null on the last page. Opaque — send it back as-is.
   */
  next: ViewReleaseIndexQueryKey | null
}

export type ViewReleaseIndexResponse = {
  /**
   * The items for the current page
   */
  items: Array<ReleaseSummary>
  meta: ViewReleaseIndexResponseMeta
}

export type ImagePullCredentials = {
  /**
   * Registry host the credentials authenticate against.
   */
  registry: string
  /**
   * Registry username — an account username, or a registry sentinel (e.g. `AWS`, `_json_key`).
   */
  username: string
}

export type CreateAppCommand = {
  /**
   * Public subdomain label + K8s object name.
   */
  slug: string
  /**
   * Fully-qualified image ref.
   */
  image: string
  /**
   * Port the container listens on.
   */
  containerPort: number
  /**
   * Replica floor. 0 lets the app sleep when idle and wake on the first request.
   */
  minReplicas?: number
  /**
   * Replica ceiling. Must be at least the floor, and at least 1.
   */
  maxReplicas?: number
  /**
   * Plain (non-secret) environment variables for the container.
   */
  env?: {
    [key: string]: string
  }
  /**
   * Registry credentials for a private image; encrypted at rest.
   */
  imagePullCredentials?: ImagePullCredentials
}

export type CreateAppResponse = {
  slug: string
  url: string
}

export type ViewAppIndexQueryKey = {
  uuid: string
}

export type ViewAppIndexPaginationQuery = {
  limit?: number
  key?: ViewAppIndexQueryKey | null
}

export type AppSummary = {
  slug: string
  image: string
  url: string
  createdAt: string
  updatedAt: string
}

export type ViewAppIndexResponseMeta = {
  /**
   * Key for the next page, or null on the last page. Opaque — send it back as-is.
   */
  next: ViewAppIndexQueryKey | null
}

export type ViewAppIndexResponse = {
  /**
   * The items for the current page
   */
  items: Array<AppSummary>
  meta: ViewAppIndexResponseMeta
}

export type ViewAppDetailResponse = {
  slug: string
  image: string
  url: string
  containerPort: number
  /**
   * 0 means the app sleeps when idle.
   */
  minReplicas: number
  maxReplicas: number
  /**
   * Saved environment variables.
   */
  env: {
    [key: string]: string
  }
  /**
   * True when the saved config differs from the newest release that has not failed, or nothing has been released.
   */
  hasUndeployedChanges: boolean
  createdAt: string
  updatedAt: string
}

export type AppHealthStatus = 'healthy' | 'degraded' | 'idle' | 'unavailable' | 'not_found'

export type ViewAppHealthResponse = {
  status: AppHealthStatus
  availableReplicas: number
  desiredReplicas: number
}

export type ViewAppLogsResponse = {
  /**
   * Pod the log was read from; null when no pod was found.
   */
  podName: string | null
  logs: string
}

export type UpdateAppCommand = {
  image?: string
  containerPort?: number
  minReplicas?: number
  maxReplicas?: number
  /**
   * Replaces the whole set — omit a key to remove it, send {} to clear.
   */
  env?: {
    [key: string]: string
  }
  /**
   * Omit to keep the stored credentials, null to clear them, an object to replace.
   */
  imagePullCredentials?: ImagePullCredentials | null
}

export type UpdateAppResponse = {
  slug: string
  image: string
  containerPort: number
  minReplicas: number
  maxReplicas: number
  env: {
    [key: string]: string
  }
}

export type ImagePullCredentialsWritable = {
  /**
   * Registry host the credentials authenticate against.
   */
  registry: string
  /**
   * Registry username — an account username, or a registry sentinel (e.g. `AWS`, `_json_key`).
   */
  username: string
  /**
   * Password or access token (PAT / API key) — placed in the dockerconfigjson `auth` field.
   */
  password: string
}

export type CreateAppCommandWritable = {
  /**
   * Public subdomain label + K8s object name.
   */
  slug: string
  /**
   * Fully-qualified image ref.
   */
  image: string
  /**
   * Port the container listens on.
   */
  containerPort: number
  /**
   * Replica floor. 0 lets the app sleep when idle and wake on the first request.
   */
  minReplicas?: number
  /**
   * Replica ceiling. Must be at least the floor, and at least 1.
   */
  maxReplicas?: number
  /**
   * Plain (non-secret) environment variables for the container.
   */
  env?: {
    [key: string]: string
  }
  /**
   * Registry credentials for a private image; encrypted at rest.
   */
  imagePullCredentials?: ImagePullCredentialsWritable
}

export type UpdateAppCommandWritable = {
  image?: string
  containerPort?: number
  minReplicas?: number
  maxReplicas?: number
  /**
   * Replaces the whole set — omit a key to remove it, send {} to clear.
   */
  env?: {
    [key: string]: string
  }
  /**
   * Omit to keep the stored credentials, null to clear them, an object to replace.
   */
  imagePullCredentials?: ImagePullCredentialsWritable | null
}

export type GetApiInfoV1Data = {
  body?: never
  path?: never
  query?: never
  url: '/api/v1/status'
}

export type GetApiInfoV1Responses = {
  200: GetApiInfoResponse
}

export type GetApiInfoV1Response = GetApiInfoV1Responses[keyof GetApiInfoV1Responses]

export type GetManifestV1Data = {
  body?: never
  path?: never
  query?: never
  url: '/api/v1/github-app/manifest'
}

export type GetManifestV1Responses = {
  200: GetManifestResponse
}

export type GetManifestV1Response = GetManifestV1Responses[keyof GetManifestV1Responses]

export type ConvertManifestV1Data = {
  body: ConvertManifestCommand
  path?: never
  query?: never
  url: '/api/v1/github-app/convert-manifest'
}

export type ConvertManifestV1Errors = {
  /**
   * Malformed body, or an invalid/expired state token.
   */
  400: unknown
  /**
   * GitHub App creation failed upstream at GitHub.
   */
  502: unknown
}

export type ConvertManifestV1Responses = {
  200: ConvertManifestResponse
}

export type ConvertManifestV1Response = ConvertManifestV1Responses[keyof ConvertManifestV1Responses]

export type CaptureInstallationV1Data = {
  body: CaptureInstallationCommand
  path?: never
  query?: never
  url: '/api/v1/github-app/capture-installation'
}

export type CaptureInstallationV1Errors = {
  /**
   * Malformed body, an unsupported setup_action, or no provisioned App.
   */
  400: unknown
  /**
   * The installation could not be verified with GitHub.
   */
  502: unknown
}

export type CaptureInstallationV1Responses = {
  200: CaptureInstallationResponse
}

export type CaptureInstallationV1Response =
  CaptureInstallationV1Responses[keyof CaptureInstallationV1Responses]

export type BeginGithubLoginV1Data = {
  body?: never
  path?: never
  query?: never
  url: '/api/v1/auth/github'
}

export type CompleteGithubLoginV1Data = {
  body: CompleteGithubLoginCommand
  path?: never
  query?: never
  url: '/api/v1/auth/github/session'
}

export type CompleteGithubLoginV1Errors = {
  /**
   * Invalid/expired OAuth state, or no provisioned App.
   */
  400: unknown
  /**
   * Could not complete login with GitHub.
   */
  502: unknown
}

export type CompleteGithubLoginV1Responses = {
  200: CompleteGithubLoginResponse
}

export type CompleteGithubLoginV1Response =
  CompleteGithubLoginV1Responses[keyof CompleteGithubLoginV1Responses]

export type ViewMeV1Data = {
  body?: never
  path?: never
  query?: never
  url: '/api/v1/auth/me'
}

export type ViewMeV1Errors = {
  /**
   * No active session.
   */
  401: unknown
  /**
   * Your account is not approved for this action.
   */
  403: unknown
}

export type ViewMeV1Responses = {
  200: ViewMeResponse
}

export type ViewMeV1Response = ViewMeV1Responses[keyof ViewMeV1Responses]

export type ViewUserIndexV1Data = {
  body?: never
  path?: never
  query?: {
    pagination?: ViewUserIndexPaginationQuery
  }
  url: '/api/v1/users'
}

export type ViewUserIndexV1Errors = {
  /**
   * No active session.
   */
  401: unknown
  /**
   * Operators only.
   */
  403: unknown
}

export type ViewUserIndexV1Responses = {
  200: ViewUserIndexResponse
}

export type ViewUserIndexV1Response = ViewUserIndexV1Responses[keyof ViewUserIndexV1Responses]

export type UpdateUserRoleV1Data = {
  body: UpdateUserRoleCommand
  path: {
    uuid: string
  }
  query?: never
  url: '/api/v1/users/{uuid}/role'
}

export type UpdateUserRoleV1Errors = {
  /**
   * Unknown role, a self-change, or demoting the last operator.
   */
  400: unknown
  /**
   * No active session.
   */
  401: unknown
  /**
   * Operators only.
   */
  403: unknown
  /**
   * No user with that uuid.
   */
  404: unknown
}

export type UpdateUserRoleV1Responses = {
  200: UpdateUserRoleResponse
}

export type UpdateUserRoleV1Response = UpdateUserRoleV1Responses[keyof UpdateUserRoleV1Responses]

export type ViewReleaseIndexV1Data = {
  body?: never
  path: {
    slug: string
  }
  query?: {
    pagination?: ViewReleaseIndexPaginationQuery
  }
  url: '/api/v1/apps/{slug}/releases'
}

export type ViewReleaseIndexV1Errors = {
  /**
   * No active session.
   */
  401: unknown
  /**
   * Your account is not approved for this action.
   */
  403: unknown
}

export type ViewReleaseIndexV1Responses = {
  200: ViewReleaseIndexResponse
}

export type ViewReleaseIndexV1Response =
  ViewReleaseIndexV1Responses[keyof ViewReleaseIndexV1Responses]

export type CreateReleaseV1Data = {
  body: CreateReleaseCommand
  path: {
    slug: string
  }
  query?: never
  url: '/api/v1/apps/{slug}/releases'
}

export type CreateReleaseV1Errors = {
  /**
   * fromReleaseUuid is not a uuid.
   */
  400: unknown
  /**
   * No active session.
   */
  401: unknown
  /**
   * Your account is not approved for this action.
   */
  403: unknown
  /**
   * No app with that slug, or no such release for it.
   */
  404: unknown
}

export type CreateReleaseV1Responses = {
  201: CreateReleaseResponse
}

export type CreateReleaseV1Response = CreateReleaseV1Responses[keyof CreateReleaseV1Responses]

export type DeployReleaseV1Data = {
  body?: never
  path: {
    uuid: string
  }
  query?: never
  url: '/api/v1/releases/{uuid}/deploy'
}

export type DeployReleaseV1Errors = {
  /**
   * No active session.
   */
  401: unknown
  /**
   * Your account is not approved for this action.
   */
  403: unknown
  /**
   * No release with that uuid.
   */
  404: unknown
  /**
   * The release is not the app’s newest release.
   */
  409: unknown
  /**
   * Stored pull credentials could not be decrypted.
   */
  500: unknown
}

export type DeployReleaseV1Responses = {
  200: DeployReleaseResponse
}

export type DeployReleaseV1Response = DeployReleaseV1Responses[keyof DeployReleaseV1Responses]

export type ViewAppIndexV1Data = {
  body?: never
  path?: never
  query?: {
    pagination?: ViewAppIndexPaginationQuery
  }
  url: '/api/v1/apps'
}

export type ViewAppIndexV1Errors = {
  /**
   * No active session.
   */
  401: unknown
  /**
   * Your account is not approved for this action.
   */
  403: unknown
}

export type ViewAppIndexV1Responses = {
  200: ViewAppIndexResponse
}

export type ViewAppIndexV1Response = ViewAppIndexV1Responses[keyof ViewAppIndexV1Responses]

export type CreateAppV1Data = {
  body: CreateAppCommandWritable
  path?: never
  query?: never
  url: '/api/v1/apps'
}

export type CreateAppV1Errors = {
  /**
   * Malformed body, or an invalid slug / image / port.
   */
  400: unknown
  /**
   * No active session.
   */
  401: unknown
  /**
   * Your account is not approved for this action.
   */
  403: unknown
  /**
   * An app with that slug already exists.
   */
  409: unknown
}

export type CreateAppV1Responses = {
  201: CreateAppResponse
}

export type CreateAppV1Response = CreateAppV1Responses[keyof CreateAppV1Responses]

export type DeleteAppV1Data = {
  body?: never
  path: {
    slug: string
  }
  query?: never
  url: '/api/v1/apps/{slug}'
}

export type DeleteAppV1Errors = {
  /**
   * No active session.
   */
  401: unknown
  /**
   * Your account is not approved for this action.
   */
  403: unknown
  /**
   * No app with that slug.
   */
  404: unknown
  /**
   * Kubernetes teardown failed; the app was kept.
   */
  502: unknown
}

export type DeleteAppV1Responses = {
  /**
   * The app and its Kubernetes resources were removed.
   */
  204: void
}

export type DeleteAppV1Response = DeleteAppV1Responses[keyof DeleteAppV1Responses]

export type ViewAppDetailV1Data = {
  body?: never
  path: {
    slug: string
  }
  query?: never
  url: '/api/v1/apps/{slug}'
}

export type ViewAppDetailV1Errors = {
  /**
   * No active session.
   */
  401: unknown
  /**
   * Your account is not approved for this action.
   */
  403: unknown
  /**
   * No app with that slug.
   */
  404: unknown
}

export type ViewAppDetailV1Responses = {
  200: ViewAppDetailResponse
}

export type ViewAppDetailV1Response = ViewAppDetailV1Responses[keyof ViewAppDetailV1Responses]

export type UpdateAppV1Data = {
  body: UpdateAppCommandWritable
  path: {
    slug: string
  }
  query?: never
  url: '/api/v1/apps/{slug}'
}

export type UpdateAppV1Errors = {
  /**
   * A field is out of range or malformed.
   */
  400: unknown
  /**
   * No active session.
   */
  401: unknown
  /**
   * Your account is not approved for this action.
   */
  403: unknown
  /**
   * No app with that slug.
   */
  404: unknown
}

export type UpdateAppV1Responses = {
  200: UpdateAppResponse
}

export type UpdateAppV1Response = UpdateAppV1Responses[keyof UpdateAppV1Responses]

export type ViewAppHealthV1Data = {
  body?: never
  path: {
    slug: string
  }
  query?: never
  url: '/api/v1/apps/{slug}/health'
}

export type ViewAppHealthV1Errors = {
  /**
   * No active session.
   */
  401: unknown
  /**
   * Your account is not approved for this action.
   */
  403: unknown
}

export type ViewAppHealthV1Responses = {
  200: ViewAppHealthResponse
}

export type ViewAppHealthV1Response = ViewAppHealthV1Responses[keyof ViewAppHealthV1Responses]

export type ViewAppLogsV1Data = {
  body?: never
  path: {
    slug: string
  }
  query?: {
    /**
     * Trailing log lines to return (default 100).
     */
    tailLines?: number
  }
  url: '/api/v1/apps/{slug}/logs'
}

export type ViewAppLogsV1Errors = {
  /**
   * tailLines out of range (1–1000) or not an integer.
   */
  400: unknown
  /**
   * No active session.
   */
  401: unknown
  /**
   * Your account is not approved for this action.
   */
  403: unknown
}

export type ViewAppLogsV1Responses = {
  200: ViewAppLogsResponse
}

export type ViewAppLogsV1Response = ViewAppLogsV1Responses[keyof ViewAppLogsV1Responses]
