// This file is auto-generated by @hey-api/openapi-ts

import * as z from 'zod'

export const zGetApiInfoResponse = z.object({
  name: z.string(),
  version: z.string(),
  commit: z.string().nullable(),
  nodeEnv: z.string(),
  uptimeSeconds: z.number(),
})

export const zGetApiInfoV1Response = zGetApiInfoResponse
