// This file is auto-generated by @hey-api/openapi-ts

import * as z from 'zod'

export const zGetApiInfoResponse = z.object({
  name: z.string(),
  version: z.string(),
  commit: z.string().nullable(),
  nodeEnv: z.string(),
  uptimeSeconds: z.number(),
})

export const zHookAttributesDto = z.object({
  url: z.string(),
})

export const zManifestDto = z.object({
  name: z.string(),
  url: z.string(),
  hook_attributes: zHookAttributesDto,
  redirect_url: z.string(),
  setup_url: z.string(),
  callback_urls: z.array(z.string()),
  public: z.boolean(),
  request_oauth_on_install: z.boolean(),
  default_permissions: z.record(z.string(), z.string()),
  default_events: z.array(z.string()),
})

export const zGetManifestResponse = z.object({
  manifest: zManifestDto,
  formAction: z.string(),
  state: z.string(),
})

export const zConvertManifestCommand = z.object({
  code: z.string(),
  state: z.string(),
})

export const zConvertManifestResponse = z.object({
  appSlug: z.string(),
  appName: z.string(),
  htmlUrl: z.string(),
  installUrl: z.string(),
})

export const zCaptureInstallationCommand = z.object({
  installationId: z.string().regex(/^\d+$/),
  setupAction: z.enum(['install']),
})

export const zCaptureInstallationResponse = z.object({
  installationId: z.string(),
  accountLogin: z.string().nullable(),
  connected: z.boolean(),
})

export const zCompleteGithubLoginCommand = z.object({
  code: z.string(),
  state: z.string(),
})

export const zCompleteGithubLoginResponse = z.object({
  id: z.string(),
  login: z.string(),
})

export const zUserRole = z.enum(['operator', 'member'])

export const zViewMeResponse = z.object({
  id: z.string(),
  login: z.string(),
  role: zUserRole,
})

export const zImagePullCredentials = z.object({
  registry: z.string().max(253),
  username: z.string().max(255),
})

export const zDeployAppCommand = z.object({
  slug: z
    .string()
    .max(63)
    .regex(/^[a-z0-9]([-a-z0-9]*[a-z0-9])?$/),
  image: z.string(),
  containerPort: z.int().gte(1).lte(65535),
  minReplicas: z.int().gte(0).lte(100).optional(),
  maxReplicas: z.int().gte(1).lte(100).optional(),
  env: z.record(z.string(), z.string()).optional(),
  imagePullCredentials: zImagePullCredentials.optional(),
})

export const zDeployStatus = z.enum(['pending', 'in_progress', 'succeeded', 'failed'])

export const zDeployAppResponse = z.object({
  appSlug: z.string(),
  url: z.string(),
  releaseUuid: z.string(),
  deployStatus: zDeployStatus,
})

export const zRedeployAppResponse = z.object({
  appSlug: z.string(),
  url: z.string(),
  releaseUuid: z.string(),
  deployStatus: zDeployStatus,
})

export const zReleaseTrigger = z.enum(['manual', 'webhook'])

export const zReleaseSummary = z.object({
  uuid: z.string(),
  imageRef: z.string(),
  triggeredBy: zReleaseTrigger,
  deployStatus: zDeployStatus,
  createdAt: z.iso.datetime(),
  updatedAt: z.iso.datetime(),
  failureReason: z.string().nullish(),
  failureMessage: z.string().nullish(),
})

export const zViewReleaseIndexResponse = z.object({
  releases: z.array(zReleaseSummary),
})

export const zAppSummary = z.object({
  slug: z.string(),
  image: z.string(),
  url: z.string(),
  createdAt: z.iso.datetime(),
  updatedAt: z.iso.datetime(),
})

export const zViewAppIndexResponse = z.object({
  apps: z.array(zAppSummary),
})

export const zViewAppDetailResponse = z.object({
  slug: z.string(),
  image: z.string(),
  url: z.string(),
  containerPort: z.int(),
  minReplicas: z.int(),
  maxReplicas: z.int(),
  env: z.record(z.string(), z.string()),
  createdAt: z.iso.datetime(),
  updatedAt: z.iso.datetime(),
})

export const zAppHealthStatus = z.enum(['healthy', 'degraded', 'idle', 'unavailable', 'not_found'])

export const zViewAppHealthResponse = z.object({
  status: zAppHealthStatus,
  availableReplicas: z.number(),
  desiredReplicas: z.number(),
})

export const zViewAppLogsResponse = z.object({
  podName: z.string().nullable(),
  logs: z.string(),
})

export const zUpdateAppEnvCommand = z.object({
  env: z.record(z.string(), z.string()),
})

export const zUpdateAppEnvResponse = z.object({
  slug: z.string(),
  env: z.record(z.string(), z.string()),
  redeployRequired: z.boolean(),
})

export const zImagePullCredentialsWritable = z.object({
  registry: z.string().max(253),
  username: z.string().max(255),
  password: z.string().max(4096),
})

export const zDeployAppCommandWritable = z.object({
  slug: z
    .string()
    .max(63)
    .regex(/^[a-z0-9]([-a-z0-9]*[a-z0-9])?$/),
  image: z.string(),
  containerPort: z.int().gte(1).lte(65535),
  minReplicas: z.int().gte(0).lte(100).optional(),
  maxReplicas: z.int().gte(1).lte(100).optional(),
  env: z.record(z.string(), z.string()).optional(),
  imagePullCredentials: zImagePullCredentialsWritable.optional(),
})

export const zGetApiInfoV1Response = zGetApiInfoResponse

export const zGetManifestV1Response = zGetManifestResponse

export const zConvertManifestV1Body = zConvertManifestCommand

export const zConvertManifestV1Response = zConvertManifestResponse

export const zCaptureInstallationV1Body = zCaptureInstallationCommand

export const zCaptureInstallationV1Response = zCaptureInstallationResponse

export const zCompleteGithubLoginV1Body = zCompleteGithubLoginCommand

export const zCompleteGithubLoginV1Response = zCompleteGithubLoginResponse

export const zViewMeV1Response = zViewMeResponse

export const zDeployAppV1Body = zDeployAppCommandWritable

export const zDeployAppV1Response = zDeployAppResponse

export const zRedeployAppV1Path = z.object({
  slug: z.string(),
})

export const zRedeployAppV1Response = zRedeployAppResponse

export const zViewReleaseIndexV1Path = z.object({
  slug: z.string(),
})

export const zViewReleaseIndexV1Response = zViewReleaseIndexResponse

export const zViewAppIndexV1Response = zViewAppIndexResponse

export const zDeleteAppV1Path = z.object({
  slug: z.string(),
})

/**
 * The app and its Kubernetes resources were removed.
 */
export const zDeleteAppV1Response = z.void()

export const zViewAppDetailV1Path = z.object({
  slug: z.string(),
})

export const zViewAppDetailV1Response = zViewAppDetailResponse

export const zViewAppHealthV1Path = z.object({
  slug: z.string(),
})

export const zViewAppHealthV1Response = zViewAppHealthResponse

export const zViewAppLogsV1Path = z.object({
  slug: z.string(),
})

export const zViewAppLogsV1Query = z.object({
  tailLines: z.int().gte(1).lte(1000).optional(),
})

export const zViewAppLogsV1Response = zViewAppLogsResponse

export const zUpdateAppEnvV1Body = zUpdateAppEnvCommand

export const zUpdateAppEnvV1Path = z.object({
  slug: z.string(),
})

export const zUpdateAppEnvV1Response = zUpdateAppEnvResponse
