// This file is auto-generated by @hey-api/openapi-ts

import * as z from 'zod'

export const zGetApiInfoResponse = z.object({
  name: z.string(),
  version: z.string(),
  commit: z.string().nullable(),
  nodeEnv: z.string(),
  uptimeSeconds: z.number(),
})

export const zHookAttributesDto = z.object({
  url: z.string(),
})

export const zManifestDto = z.object({
  name: z.string(),
  url: z.string(),
  hook_attributes: zHookAttributesDto,
  redirect_url: z.string(),
  callback_urls: z.array(z.string()),
  public: z.boolean(),
  request_oauth_on_install: z.boolean(),
  default_permissions: z.record(z.string(), z.string()),
  default_events: z.array(z.string()),
})

export const zGetManifestResponse = z.object({
  manifest: zManifestDto,
  formAction: z.string(),
  state: z.string(),
})

export const zConvertManifestCommand = z.object({
  code: z.string(),
  state: z.string(),
})

export const zConvertManifestResponse = z.object({
  appSlug: z.string(),
  appName: z.string(),
  htmlUrl: z.string(),
  installUrl: z.string(),
})

export const zCaptureInstallationCommand = z.object({
  installationId: z.string().regex(/^\d+$/),
  setupAction: z.enum(['install']),
})

export const zCaptureInstallationResponse = z.object({
  installationId: z.string(),
  accountLogin: z.string().nullable(),
  connected: z.boolean(),
})

export const zCompleteGithubLoginCommand = z.object({
  code: z.string(),
  state: z.string(),
})

export const zCompleteGithubLoginResponse = z.object({
  id: z.string(),
  login: z.string(),
})

export const zUserRole = z.enum(['operator', 'member'])

export const zGetCurrentUserResponse = z.object({
  id: z.string(),
  login: z.string(),
  role: zUserRole,
})

export const zDeployAppCommand = z.object({
  slug: z.string(),
  image: z.string(),
  containerPort: z.number(),
  replicas: z.number().optional(),
  env: z.record(z.string(), z.string()).optional(),
})

export const zReleaseStatus = z.enum(['pending', 'in_progress', 'succeeded', 'failed'])

export const zDeployAppResponse = z.object({
  appSlug: z.string(),
  url: z.string(),
  releaseUuid: z.string(),
  status: zReleaseStatus,
})

export const zGetApiInfoV1Response = zGetApiInfoResponse

export const zGetGithubAppManifestV1Response = zGetManifestResponse

export const zConvertGithubAppManifestV1Body = zConvertManifestCommand

export const zConvertGithubAppManifestV1Response = zConvertManifestResponse

export const zCaptureGithubAppInstallationV1Body = zCaptureInstallationCommand

export const zCaptureGithubAppInstallationV1Response = zCaptureInstallationResponse

export const zCompleteGithubLoginV1Body = zCompleteGithubLoginCommand

export const zCompleteGithubLoginV1Response = zCompleteGithubLoginResponse

export const zGetCurrentUserV1Response = zGetCurrentUserResponse

export const zDeployAppV1Body = zDeployAppCommand

export const zDeployAppV1Response = zDeployAppResponse
